### REGISTER
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Jim",
  "username": "Jim",
  "email": "jima7@gmail.com",
  "password": "12345678"
}

### LOGIN
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "jim1@gmail.com",
  "password": "12345678"
}

### LOGOUT
POST http://localhost:3000/users/logout

### GET USERS
GET http://localhost:3000/users
Authorization: Bearer {{ access_token }}
